### ISSUE TITLE
How can i get this module , while discordapp doesn't working on my city(or country) network ?

### ISSUE THREAD

**Issue by betayi** [55Honey/Acore_CustomWorldboss#1]
as the title , how to connect without discord app ?

**Comment by Helias** [comment]
Hello, watching your profile I saw that you opened different issues, a Pull Request which can grant you to be rank 1, but to get this lua module you need to be rank 3, so more contributions from your side.

It's not an issue that you cannot use the discord app, the only thing is that it's hard to keep track of your rank in this way
